spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/deokhugam
    username: deokhugam
    password: deokhugam
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    com.codeit.team4: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

user:
  cleanup:
    cron: "0 */5 * * * *"
    zone: "Asia/Seoul"

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    book-search-url: https://openapi.naver.com/v1/search/book_adv.json

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}