spring:
  application:
    name: deokhugam
  profiles:
    default: local
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

server:
  tomcat:
    uri-encoding: UTF-8

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info
  cloudwatch:
    metrics:
      export:
        enabled: false

app:
  client-ip-headers: X-Forwarded-For,Proxy-Client-IP,WL-Proxy-Client-IP,HTTP_CLIENT_IP,HTTP_X_FORWARDED_FOR